#!/bin/bash

TESTSCRIPT=$1

ansible-checkout-versions

CWD=$(pwd)
VERSIONS=$(ansible-list-versions)
BASEDIR=/tmp

RESULTS=""
LOGFILE="returncodes.txt"
rm -f $LOGFILE

for VERSION in $VERSIONS; do
    (
    echo "###################################"
    echo $VERSION
    echo "###################################"
    VERSIONDIR="$BASEDIR/ansible.$VERSION"
    HACKING="$VERSIONDIR/hacking/env-setup"
    if [ -f $HACKING ]; then
        source $(which ansible-clear-hacking)
        source $HACKING > /dev/null 2>&1
    fi

    bash $TESTSCRIPT
    RC=$?

    echo ""
    echo "$VERSION ; $RC" >> $LOGFILE
    echo ""
    )
done

cat $LOGFILE
