#!/bin/bash

CWD=$(pwd)
CACHEDIR=/var/cache/ansible/ansible.checkout.clean
if [ ! -d $CACHEDIR ]; then
    git clone https://github.com/ansible/ansible.git \
        --recursive $CACHEDIR >/dev/null 2>&1
else
    cd $CACHEDIR
    git pull --recurse-submodules >/dev/null 2>&1
fi

cd $CACHEDIR
VERSIONS=$(git tag -l | fgrep -v alpha | fgrep -v beta)

for VERSION in $VERSIONS; do
    echo $VERSION
done
