#!/bin/bash

TESTSCRIPT=$1

ansible-checkout-versions

CWD=$(pwd)
VERSIONS=$(ansible-list-versions)
BASEDIR=/var/cache/ansible/version_checkouts
CACHEDIR=/var/cache/ansible/ansible.checkout.clean

RESULTS=""
LOGFILE="returncodes.txt"
rm -f $LOGFILE

for VERSION in $VERSIONS; do
    (
    echo "###################################"
    echo $VERSION
    echo "###################################"

    echo $VERSION > ansible.version

    if [[ $VERSION == "devel"* ]]; then
        VERSIONDIR="$CACHEDIR"
    else
        VERSIONDIR="$BASEDIR/ansible.$VERSION"
    fi
    HACKING="$VERSIONDIR/hacking/env-setup"
    if [ -f $HACKING ]; then
        source $(which ansible-clear-hacking)
        source $HACKING > /dev/null 2>&1
    else
        echo "ERROR: env-setup does not exist for $VERSIONDIR"
        exit 1
    fi

    bash $TESTSCRIPT
    RC=$?

    echo ""
    echo "$VERSION ; $RC" >> $LOGFILE
    echo ""
    )
done

cat $LOGFILE
