#!/bin/bash

CWD=$(pwd)
VERSIONS=$(ansible-list-versions)
CACHEDIR=/var/cache/ansible/ansible.checkout.clean
BASEDIR=/var/cache/ansible/version_checkouts

if [ ! -d $BASEDIR ]; then
    mkdir -p $BASEDIR
fi

for VERSION in $VERSIONS; do
    echo $VERSION

    if [[ $VERSION != "devel"* ]]; then

        # git checkout tags/<tag_name>
        CHECKOUTDIR="$BASEDIR/ansible.$VERSION"
        if [ ! -d $CHECKOUTDIR ]; then
            cp -Rp $CACHEDIR $CHECKOUTDIR
            cd $CHECKOUTDIR

            # submodules start at v1.8.0
            if [[ $VERSION < v1.8.0 ]]; then
                echo "## deleting submodules ..."
                rm -rf rm -rf lib/ansible/modules/*
            fi
            
            echo "## checking out tag ..."
            git checkout tags/$VERSION
            RC=$?
            if [[ $RC != 0 ]]; then
                exit $RC
            fi

            if [[ $VERSION > v1.7.2 ]]; then
                echo "## updating submodules ..."
                git submodule update
                RC=$?
                if [[ $RC != 0 ]]; then
                    exit $RC
                fi
            fi            
        fi
    fi 
    cd $CWD
done
