#!/usr/bin/env python2

# A tool to check the order of precedence for ansible variables
#
#    TOTAL: 20
#    1. extra_vars
#    2. set_fact
#    3. include_vars
#    4. role_var
#    5. vars_file
#    6. play_var
#    7. pb_host_vars_file
#    8. ini_group_vars_file_parent
#    9. ini_group_vars_file_child
#    10. ini_group_vars_file_all
#    11. ini_host_vars_file
#    12. ini_host
#    13. pb_group_vars_file_child
#    14. pb_group_vars_file_parent
#    15. ini_child
#    16. ini_parent
#    17. ini_all
#    18. pb_group_vars_file_all
#    19. role_parent_default
#    20. role_default

import os
import sys
import shutil
import subprocess
import tempfile
from pprint import pprint

TESTDIR = tempfile.mkdtemp()

def run_command(args, cwd=None):
    p = subprocess.Popen(
            args, 
            stderr=subprocess.PIPE, 
            stdout=subprocess.PIPE, 
            shell=True,
            cwd=cwd
        )
    (so, se) = p.communicate()
    return (p.returncode, so, se)

def clean_test_dir():
    if os.path.isdir(TESTDIR):
        shutil.rmtree(TESTDIR)
    os.makedirs(TESTDIR)

class Role(object):
    def __init__(self, name):
        self.name = name
        self.load = True
        self.dependencies = []
        self.defaults = False
        self.vars = False
        self.tasks = []

    def write_role(self):

        fpath = os.path.join(TESTDIR, 'roles', self.name)
        if not os.path.isdir(fpath):
            os.makedirs(fpath)

        if self.defaults:
            # roles/x/defaults/main.yml
            fpath = os.path.join(TESTDIR, 'roles', self.name, 'defaults')
            if not os.path.isdir(fpath):
                os.makedirs(fpath)
            fname = os.path.join(fpath, 'main.yml')
            with open(fname, 'wb') as f:
                f.write('findme: %s\n' % self.name)

        if self.vars:
            # roles/x/vars/main.yml
            fpath = os.path.join(TESTDIR, 'roles', self.name, 'vars')
            if not os.path.isdir(fpath):
                os.makedirs(fpath)
            fname = os.path.join(fpath, 'main.yml')
            with open(fname, 'wb') as f:
                f.write('findme: %s\n' % self.name)

        if self.dependencies:
            fpath = os.path.join(TESTDIR, 'roles', self.name, 'meta') 
            if not os.path.isdir(fpath):
                os.makedirs(fpath)
            fname = os.path.join(fpath, 'main.yml')
            with open(fname, 'wb') as f:
                f.write('dependencies:\n')
                for dep in self.dependencies:
                    f.write('- { role: %s }\n' % dep)                    
            #import epdb; epdb.st()

class VarTestMaker(object):
    def __init__(self, features):
        clean_test_dir()
        self.features = features
        self.inventory = ''
        self.playvars = []
        self.varsfiles = []
        self.playbook =  '- hosts: testhost\n'
        self.playbook += '  gather_facts: False\n'
        self.tasks = []
        self.roles = []

    def write_playbook(self):
        fname = os.path.join(TESTDIR, 'site.yml')
        with open(fname, 'wb') as f:
            f.write(self.playbook)
            if self.playvars:
                f.write('  vars:\n')
                for pv in self.playvars:
                    f.write('    %s\n' % pv)
            if self.varsfiles:
                f.write('  vars_files:\n')
                for vf in self.varsfiles:
                    f.write('    - %s\n' % vf)
            if self.roles:
                f.write(    '  roles:\n')
                for role in self.roles:
                    #print("writing %s" % role.name)
                    role.write_role()
                    if role.load:
                        f.write('    - %s\n' % role.name)
            if self.tasks:
                f.write(    '  tasks:\n')
                for task in self.tasks:
                    f.write('    - %s\n' % task)

    def run(self):

        if 'ini_host' in self.features:
            self.inventory += 'testhost findme=ini_host\n'            
        else:
            self.inventory += 'testhost\n'            
        self.inventory += '\n'

        if 'ini_child' in self.features:
            self.inventory += '[child]\n'
            self.inventory += 'testhost\n' 
            self.inventory += '\n'
            self.inventory += '[child:vars]\n'
            self.inventory += 'findme=ini_child\n'
            self.inventory += '\n'

        if 'ini_parent' in self.features:
            if 'ini_child' in self.features:
                self.inventory += '[parent:children]\n'
                self.inventory += 'child\n'
            else:
                self.inventory += '[parent]\n'
                self.inventory += 'testhost\n'
            self.inventory += '\n'
            self.inventory += '[parent:vars]\n'
            self.inventory += 'findme=ini_parent\n'
            self.inventory += '\n'

        if 'ini_all' in self.features:
            self.inventory += '[all:vars]\n'
            self.inventory += 'findme=ini_all\n'
            self.inventory += '\n'

        # default to a single file called inventory
        invfile = os.path.join(TESTDIR, 'inventory', 'hosts')
        ipath = os.path.join(TESTDIR, 'inventory')
        if not os.path.isdir(ipath):
            os.makedirs(ipath)

        if 'ini_host_vars_file' in self.features:
            hpath = os.path.join(TESTDIR, 'inventory', 'host_vars')
            if not os.path.isdir(hpath):
                os.makedirs(hpath)
            hfile = os.path.join(hpath, 'testhost')
            with open(hfile, 'wb') as f:
                f.write('findme: ini_host_vars_file\n')
        
        if 'ini_group_vars_file_all' in self.features:
            gpath = os.path.join(TESTDIR, 'inventory', 'group_vars')
            if not os.path.isdir(gpath):
                os.makedirs(gpath)
            gfile = os.path.join(gpath, 'all')
            with open(hfile, 'wb') as f:
                f.write('findme: ini_group_vars_file_all\n')

        if 'ini_group_vars_file_child' in self.features:
            gpath = os.path.join(TESTDIR, 'inventory', 'group_vars')
            if not os.path.isdir(gpath):
                os.makedirs(gpath)
            gfile = os.path.join(gpath, 'child')
            with open(hfile, 'wb') as f:
                f.write('findme: ini_group_vars_file_child\n')
        
        if 'ini_group_vars_file_parent' in self.features:
            gpath = os.path.join(TESTDIR, 'inventory', 'group_vars')
            if not os.path.isdir(gpath):
                os.makedirs(gpath)
            gfile = os.path.join(gpath, 'child')
            with open(hfile, 'wb') as f:
                f.write('findme: ini_group_vars_file_parent\n')

        with open(invfile, 'wb') as f:
            f.write(self.inventory)

        if 'pb_host_vars_file' in self.features:
            os.makedirs(os.path.join(TESTDIR, 'host_vars'))
            fname = os.path.join(TESTDIR, 'host_vars', 'testhost')
            with open(fname, 'wb') as f:
                f.write('findme: pb_host_vars_file\n')

        if 'pb_group_vars_file_parent' in self.features:
            if not os.path.isdir(os.path.join(TESTDIR, 'group_vars')):
                os.makedirs(os.path.join(TESTDIR, 'group_vars'))
            fname = os.path.join(TESTDIR, 'group_vars', 'parent')
            with open(fname, 'wb') as f:
                f.write('findme: pb_group_vars_file_parent\n')

        if 'pb_group_vars_file_child' in self.features:
            if not os.path.isdir(os.path.join(TESTDIR, 'group_vars')):
                os.makedirs(os.path.join(TESTDIR, 'group_vars'))
            fname = os.path.join(TESTDIR, 'group_vars', 'child')
            with open(fname, 'wb') as f:
                f.write('findme: pb_group_vars_file_child\n')

        if 'pb_group_vars_file_all' in self.features:
            if not os.path.isdir(os.path.join(TESTDIR, 'group_vars')):
                os.makedirs(os.path.join(TESTDIR, 'group_vars'))
            fname = os.path.join(TESTDIR, 'group_vars', 'all')
            with open(fname, 'wb') as f:
                f.write('findme: pb_group_vars_file_all\n')

        if 'play_var' in self.features:
            self.playvars.append('findme: play_var')

        if 'set_fact' in self.features:
            self.tasks.append('set_fact: findme="set_fact"')

        if 'vars_file' in self.features:
            self.varsfiles.append('varsfile.yml')
            fname = os.path.join(TESTDIR, 'varsfile.yml')
            with open(fname, 'wb') as f:
                f.write('findme: vars_file\n')

        if 'include_vars' in self.features:
            self.tasks.append('include_vars: included.yml')
            fname = os.path.join(TESTDIR, 'included.yml')
            with open(fname, 'wb') as f:
                f.write('findme: include_vars\n')

        if 'role_var' in self.features:
            role = Role('role_var')
            role.vars = True
            role.load = True
            self.roles.append(role)

        if 'role_parent_default' in self.features:
            role = Role('role_default')
            role.load = False
            role.defaults = True
            self.roles.append(role)

            role = Role('role_parent_default')
            role.dependencies.append('role_default')
            role.defaults = True
            role.load = True
            self.roles.append(role)

        elif 'role_default' in self.features:
                role = Role('role_default')
                role.defaults = True
                role.load = True
                self.roles.append(role)
        
        #print(self.features)
        #pprint([(x.name,x.load) for x in self.roles])

        self.tasks.append('debug: var=findme')
        self.write_playbook()

        cmd = 'ansible-playbook -c local -i inventory site.yml'
        if 'extra_vars' in self.features:
            cmd += ' --extra-vars="findme=extra_vars"'
        (rc, so, se) = run_command(cmd, cwd=TESTDIR)

        if rc == 0:
            val = None
            try:
                idx = so.rfind('findme')
                val = so[idx:]
                val = val.split('"')[2]
            except Exception as e:
                print(e)
                import epdb; epdb.st()
            return val
        else:
            print(se)
            import epdb; epdb.st()
            sys.exit(1)
            return False


def main():
    results = []
    features = ['ini_host', 
                'ini_child', 
                'ini_parent',
                'ini_all',
                'ini_host_vars_file',
                'ini_group_vars_file_parent',
                'ini_group_vars_file_child',
                'ini_group_vars_file_all',
                'pb_group_vars_file_parent', 
                'pb_group_vars_file_child',
                'pb_group_vars_file_all',
                'pb_host_vars_file',
                'play_var',
                'role_parent_default',
                'role_default',
                'role_var',
                'include_vars',
                'set_fact',
                'vars_file',
                'extra_vars']

    print("TOTAL: %s" % len(features))

    last_removed = None
    index = 1
    while features:
        res = VarTestMaker(features).run()
        if not res or res == 'VARIABLE IS NOT DEFINED!':
            print("ERROR: %s" % res)
            print("tempdir: %s" % TESTDIR)
            print("last_removed: %s" % last_removed)
            print("features: %s" % features)
            sys.exit(1)

        print('%s. %s' % (index, res))
        try:
            features.remove(res)
        except Exception as e:
            print("ERROR !!!")
            print(e)
            print('features: %s' % features)
            print('res: %s' % res)
            sys.exit(1)
        last_removed = res
        index += 1

    shutil.rmtree(TESTDIR)

if __name__ == "__main__":
    main()

