#!/bin/bash
tc qdisc add dev eth1 root handle 1: prio priomap 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
tc qdisc add dev eth1 parent 1:2 handle 20: netem delay 999ms
tc filter add dev eth1 parent 1:0 protocol ip u32 match ip dport $1 0xffff flowid 1:2
