#!/bin/bash

INVERSION=$1
TESTSCRIPT=$2

#echo "# running ansible-checkout-versions ..."
#ansible-checkout-versions

echo "# running ansible-list-versions ..."
CWD=$(pwd)
if [[ $INVERSION == "devel"* ]]; then
    VERSION=$(ansible-list-versions | fgrep $INVERSION | tail -n1)
else
    VERSION=$(ansible-list-versions | egrep ^$INVERSION | tail -n1)
fi

ADTBASE=$(ansible-tools-config --cachedir)
BASEDIR=$ADTBASE/extracted
CACHEDIR=$ADTBASE/checkouts/ansible-devel

(
echo "###################################"
echo $VERSION
echo "###################################"

echo $VERSION > ansible.version

if [[ $VERSION == "devel"* ]]; then
    VERSIONDIR="$CACHEDIR"
else
    VERSIONDIR="$BASEDIR/ansible-$VERSION"
fi
echo "# running  $VERSIONDIR/hacking/env-setup ..."
HACKING="$VERSIONDIR/hacking/env-setup"
if [ -f $HACKING ]; then
    source $HACKING > /dev/null 2>&1
else
    echo "ERROR: env-setup does not exist for $VERSIONDIR"
    exit 1
fi

echo "# $(pwd)"
chmod +x $TESTSCRIPT
./$TESTSCRIPT
RC=$?
echo "## RC: $RC"
)

exit $RC
