#!/usr/bin/env python

import argparse
import os

from ansible_dev_tools.config import ANSIBLE_DEV_TOOLS_CACHEDIR
from ansible_dev_tools.config import ANSIBLE_DEV_TOOLS_WORKDIR
from ansible_dev_tools.config import ANSIBLE_DEV_TOOLS_WORKDIR_CURRENT


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--cachedir', action='store_true')    
    parser.add_argument('--workdir', action='store_true')    
    parser.add_argument('--current-workdir', action='store_true')    
    args = parser.parse_args()

    if args.cachedir:
        print(ANSIBLE_DEV_TOOLS_CACHEDIR)
    elif args.workdir:
        print(ANSIBLE_DEV_TOOLS_WORKDIR)
    elif args.current_workdir:
        print(ANSIBLE_DEV_TOOLS_WORKDIR_CURRENT)


if __name__ == "__main__":
    main()
