#!/usr/bin/env python

import argparse
import os

from ansible_tools.config import ANSIBLE_TOOLS_CACHEDIR


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--cachedir', action='store_true')    
    args = parser.parse_args()

    if args.cachedir:
        print(ANSIBLE_TOOLS_CACHEDIR)


if __name__ == "__main__":
    main()
