#!/usr/bin/env python

import argparse
from ansible_dev_tools.utils import AnsibleVersionTester


def main():

    parser = argparse.ArgumentParser()
    parser.add_argument('--start', help='skip testing versions up to this version')
    parser.add_argument('--version', help='the ansible version to use')
    parser.add_argument('--python', help='python interpreter to use')
    parser.add_argument('script', nargs='+', help='the test script or scripts to use')
    args = parser.parse_args()

    avt = AnsibleVersionTester()
    avt.run_test(
        start=args.start,
        version=args.version,
        python=args.python,
        command=' '.join(args.script)
    )


if __name__ == "__main__":
    main()
